---
title: "Support"
editor: visual
---

## Academic support

Writing Center GW's Writing Center cultivates confident writers in the
University community by facilitating collaborative, critical, and
inclusive conversations at all stages of the writing process. Working
alongside peer mentors, writers develop strategies to write
independently in academic and public settings. Appointments can be
booked online [here](https://writingcenter.gwu.edu/appointments).

Academic Commons Academic Commons provides tutoring and other academic
support resources to students in many courses. Students can schedule
virtual one-on-one appointments or attend virtual drop-in sessions.
Students may schedule an appointment, review the tutoring schedule,
access other academic support resources, or obtain assistance
[here](https://academiccommons.gwu.edu).

## Support for students outside the classroom

Disability Support Services (DSS) 202-994-8250 Any student who may need
an accommodation based on the potential impact of a disability should
contact [Disability Support Services](https://disabilitysupport.gwu.edu)
to establish eligibility and to coordinate reasonable accommodations.

Counseling and Psychological Services 202-994-5300 GW's [Colonial Health
Center](https://healthcenter.gwu.edu/counseling-and-psychological-services)
offers counseling and psychological services, supporting mental health
and personal development by collaborating directly with students to
overcome challenges and difficulties that may interfere with academic,
emotional, and personal success.

GW aims to create a community that cares for each other.The [CARE
Team](https://studentlife.gwu.edu/care-team) fosters this goal by
creating a pathway through which students who may need additional
support can be identified and referred to the most appropriate services.
Through the CARE Team, students are given the support they need to
persist and succeed at GW and beyond.

Safety and Security:

-   In an emergency: call GWPD 202-994-6111 or 911.
-   For situation-specific actions: review the [Emergency Response
    Handbook](https://safety.gwu.edu/emergency-response-handbook)
-   Stay informed:
    [safety.gwu.edu/stay-informed](https://safety.gwu.edu/stay-informed)
