---
title: "Course Schedule"
tbl-colwidths: [5,10,20,20,25,5,5,5,5]
editor: visual
---

```{r}
#| label: setup
#| include: false
library(lubridate)

mon <- as_date("2023-05-22")
tues <- mon+days(1)
wed <- mon+days(2)
thur <- mon+days(3)
fri <- mon+days(4)
sat <- mon+days(5)

advdate <- function(day, week) {
  date <- (day + weeks(week))
  dm <- paste(month(date, label = TRUE)," ",day(date))
  return(dm)  
}
```

This page displays an outline of the topics, content, and assignments
for the term. Each module starts on a Monday. There are no assignments
due on Sundays.

::: column-screen-inset-right
|                                        Module                                         | Date                | Skills                       | Packages                                                     | Functions                                                                                                                                                                           |                                      Readings                                       |                                                           Reference                                                           | Videos                                                                                                                                                      |                                                                     Assignments                                                                      |
|:------:|--------|--------|--------|--------|:------:|:------:|--------|:------:|
|                     [1.1](/modules/module-1.1.html "Module 1.1")                      | `r advdate(mon,0)`  | Read data into R             | `readr`, `dplyr`                                             | `read_csv()`, `glimpse()`                                                                                                                                                           |                                                                                     |                          [ðŸ“–](https://r4ds.hadley.nz/data-import.html#introduction "r4ds 8.1 & 8.2")                          | [ðŸ–¥ï¸](https://youtu.be/YLOaKB8dfF4 "Downloading World Bank data")[ðŸ–¥ï¸](https://youtu.be/XOGXn8IiHK8 "Reading data from a flat file")                          |                                                                                                                                                      |
|                                                                                       | `r advdate(tues,0)` | Reshape data                 | `tidyr`                                                      | `pivot_longer()`                                                                                                                                                                    |                                                                                     |                                 [ðŸ“–](https://r4ds.hadley.nz/data-tidy.html "r4ds 6.1 & 6.3")                                  | [ðŸ–¥ï¸](https://youtu.be/ud36szsO9a4 "Reshaping data")                                                                                                         |                                                                                                                                                      |
|                                                                                       | `r advdate(wed,0)`  | Clean data                   | `dplyr`                                                      | `mutate()`, `mutate_at()`, `substring()`                                                                                                                                            |    [ðŸ“–](https://link.springer.com/article/10.1057/palgrave.ap.5500151 "Norris")     |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/syG5cdmtXSo "Truncating strings, changing variable types")[ðŸ–¥ï¸](https://youtu.be/M-uuPBdBCTw "Cleaning variable names")                |                                 [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 1.1. quiz")                                  |
|                     [1.2](/modules/module-1.2.html "Module 1.2")                      | `r advdate(thur,0)` | Download data from an API    | `wbstats`, `vdemdata`, `dplyr`, `janitor`                    | `wb_data()`, `vdem`, `select_()`, `filter()`, `case_match()`, `round_to_fraction()`                                                                                                 |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/cBRTP2imt_o "Dowload data from the World Bank")[ðŸ–¥ï¸](https://youtu.be/7CvYTeMP_PU "Filter data and select variables")                  |                                                                                                                                                      |
|                                                                                       | `r advdate(fri,0)`  | Merge data frames            | `countrycode`, `dplyr` , `readr`                             | `countrycode()`, `left_join()`, `write_csv()`                                                                                                                                       |                                                                                     |                            [ðŸ“–](https://r4ds.hadley.nz/joins.html#sec-mutating-joins "r4ds, 20.3")                            | [ðŸ–¥ï¸](https://youtu.be/ZGD0kO_iwAM "Add country codes to data frame")[ðŸ–¥ï¸](https://youtu.be/wNF3ZPneHWw "Merge two data frames")                              |                                                                                                                                                      |
|                                                                                       | `r advdate(sat,0)`  | Group, summarize and arrange | `dplyr`                                                      | `group_by()`, `summarize()`, `arrange()`                                                                                                                                            |                                                                                     |                              [ðŸ“–](https://r4ds.hadley.nz/data-transform.html#groups "r4ds, 4.5")                              | [ðŸ–¥ï¸](https://youtu.be/2nX9p6arQjg "Group, summarize and arrange")                                                                                           | [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 1.2 quiz")[ðŸ§®](/assignments/coding-assignment-1.html "Coding assignment 1")  |
|                     [2.1](/modules/module-2.1.html "Module 2.1")                      | `r advdate(mon,1)`  | Bar charts & histograms      | `ggplot2`                                                    | `ggplot()`, `geom_col()`, `geom_histogram()`, `aes()`, `labs()`                                                                                                                     |                                                                                     | [ðŸ“–](https://r4ds.hadley.nz/data-visualize.html "r4ds, 2")[ðŸ“–](https://r4ds.hadley.nz/communication.html#labels "r4ds, 12.2") | [ðŸ–¥ï¸](https://youtu.be/hl02sVTyCRA "Bar charts")[ðŸ–¥ï¸](https://youtu.be/LuNDAIQXx9w "Histograms")                                                              |                                                                                                                                                      |
|                                                                                       | `r advdate(tues,1)` | Line charts                  | `ggplot2`                                                    | `geom_line()`                                                                                                                                                                       |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/cHos9y261SQ "Line charts")                                                                                                            |                                                                                                                                                      |
|                                                                                       | `r advdate(wed,1)`  | Scatter plots                | `ggplot2`, `scales`                                          | `geom_point()`, `geom_smooth()`, `scale_x_log10(),` `label_number()`, `geom_text()`                                                                                                 |     [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/1951731?seq=8 "Lipset")      |                                  [ðŸ“–](https://r4ds.hadley.nz/layers.html "r4ds, 10.1-10.4")                                   | [ðŸ–¥ï¸](https://youtu.be/Cvme3C268wE "Scatter plots")                                                                                                          |                                  [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 2.1 quiz")                                  |
|                     [2.2](/modules/module-2.2.html "Module 2.2")                      | `r advdate(thur,1)` | Color schemes                | `tidyr`, `colorBlindess`, `dplyr`, `viridis`, `RColorBrewer` | `drop_na()`, `cvdPlot()`, `scale_fill_manual()`, `scale_fill_viridis_d()`, `scale_fill_brewer()`, `scale_color_manual()`, `scale_color_viridis_d()`, `scale_color_brewer`           |                                                                                     |                              [ðŸ“–](https://r4ds.hadley.nz/communication.html#scales "r4ds, 12.4")                              | [ðŸ–¥ï¸](https://youtu.be/fBCtSjg_-Ik "Color schemes")                                                                                                          |                                                                                                                                                      |
|                                                                                       | `r advdate(fri,1)`  | Themes & annotations         | `ggplot2`                                                    | `theme_dark()`, `theme_minimal()`, `annotate()`, `geom_hline()`, `geom_vline()`                                                                                                     |                                                                                     |                        [ðŸ“–](https://r4ds.hadley.nz/communication.html#annotations "r4ds, 12.3 & 12.5")                        | [ðŸ–¥ï¸](https://youtu.be/Le0OJXdsy3o "Themes")[ðŸ–¥ï¸](https://youtu.be/uEpBMgWilXc "Annotations")                                                                 |                                                                                                                                                      |
|                                                                                       | `r advdate(sat,1)`  | Interactivity                | `plotly`                                                     | `ggplotly()`, `layout()`                                                                                                                                                            |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/T-7jtbcwaJ0 "Interactivity")                                                                                                          | [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 2.2 quiz") [ðŸ§®](/assignments/coding-assignment-2.html "Coding assignment 2") |
|                     [3.1](/modules/module-3.1.html "Module 3.1")                      | `r advdate(mon,2)`  | Choropleth maps              | `rnaturalearth`, `ggplot2`, `ggthemes`                       | `ne_countries()`, `geom_sf()`, `theme_map()`                                                                                                                                        |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/HB3PMF93hzs "Choropleth maps")                                                                                                        |                                                                                                                                                      |
|                                                                                       | `r advdate(tues,2)` | Map data                     | `ggplot2`, `viridis`                                         | `theme()`, `scale_fill_viridis_c()`                                                                                                                                                 |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/5RnnGov3Iw4 "Map World Bank data")                                                                                                    |                                                                                                                                                      |
|                                                                                       | `r advdate(wed,2)`  | Make a map function          |                                                              | `eval()`, `parse()`, `function()`, `source()`                                                                                                                                       | [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctt7s3wz.10 "Ross, Chapter 3") |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/m42vrbEEHT4 "Turn your map into a function")                                                                                          |                                  [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 3.1 quiz")                                  |
| [3](/modules/module-3.1.html "Module 3.1")[.2](/modules/module-3.2.html "Module 3.2") | `r advdate(thur,2)` | Upload UCDP data             | `states`, `sf`                                               | `sfind()`, `st_as_sf()`                                                                                                                                                             |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/If2PwFv90iI "Upload UCDP data")                                                                                                       |                                                                                                                                                      |
|                                                                                       | `r advdate(fri,2)`  | Make a leaflet map           | `leaflet`                                                    | `leaflet()`, `addTiles()`, `addMarkers()`, `setView()`                                                                                                                              |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/hHUPqgHRqYU "Make a leaflet map")                                                                                                     |                                                                                                                                                      |
|                                                                                       | `r advdate(sat,2)`  | Customize your map           | `leaflet`, `htmltools`                                       | `awesomeIcons()`, `addAwesomeMarkers(),` `addProviderTiles()`, `sprintf()`, `lapply()`, `HTML`                                                                                      |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](https://youtu.be/qLYeSsoDvgs "Customize your map")                                                                                                     | [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 3.2 quiz") [ðŸ§®](/assignments/coding-assignment-3.html "Coding assignment 3") |
|                     [4.1](/modules/module-4.1.html "Module 4.1")                      | `r advdate(mon,3)`  | Exploring tabular data       | `tidycensus`, `dplyr`, `stringr`, `kableExtra`               | `census_api_key()`, `load_variables()`, `get_acs()`, `rename()`, `rename_with`, `str_remove()`, `kable()`, `slice_max()`, `slice_min()`, `slice_sample()`, `bind_rows()`            |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](Working%20with%20tidycensus "https://www.youtube.com/embed/wo9vZccmqwc")[ðŸ–¥ï¸](https://www.youtube.com/embed/wo9vZccmqwc "Explore data with kableExtra") |                                                                                                                                                      |
|                                                                                       | `r advdate(tues,3)` | Make a `gt` table            | `gt`                                                         | `gt()`, `tab_header()`, `cols_label()`, `fmt_currency()`, `tab_source_note()`, `cols_width()`, `opt_table_font()`, `cols_align()`, `tab_options()`, `gtsave()`                      |                                                                                     |                                                                                                                               | [ðŸ–¥ï¸](https://www.youtube.com/embed/wo9vZccmqwc "Make a gt table")                                                                                           |                                                                                                                                                      |
|                                                                                       | `r advdate(wed,3)`  | Confidence intervals         | `ggplot2`                                                    | `geom_errorbar()`                                                                                                                                                                   |            [ðŸ“–](https://www.jstor.org/stable/3118222 "Fearon & Laitin")             |                                                                                                                               | [ðŸ–¥ï¸](https://www.youtube.com/embed/wo9vZccmqwc "Make a coefficient plot")                                                                                   |                                  [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 4.1 quiz")                                  |
|                     [4.2](/modules/module-4.2.html "Module 4.2")                      | `r advdate(thur,3)` | Display regression tables    | `peacesciencer`, `broom`, `dplyr`                            | `create_stateyears()`, `add_ucdp_acd()`, `add_democracy()`, `add_creg_fractionalization()`, `add_sdp_gdp()`, `add_rugged_terrain()`, `tidy()`, `mutate_if()`, `glm()`, `binomial()` |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          |                                                                                                                                                      |
|                                                                                       | `r advdate(fri,3)`  | Make regression tables       | `modelsummary`                                               | `list()`, `modelsummary()`                                                                                                                                                          |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          |                                           [âœï¸](/project/project-assignment-1.html "Project assignment 1")                                            |
|                                                                                       | `r advdate(sat,3)`  | Coefficient plots            | `modelsummary`                                               | `modelplot()`, `rev()`                                                                                                                                                              |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          | [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 4.2 quiz") [ðŸ§®](/assignments/coding-assignment-4.html "Coding assignment 4") |
|                     [5.1](/modules/module-5.1.html "Module 5.1")                      | `r advdate(mon,4)`  | Scatter plot app setup       | `dplyr`                                                      | `summarize_all()`                                                                                                                                                                   |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          |                                                                                                                                                      |
|                                                                                       | `r advdate(tues,4)` | Building the UI              | `shiny`                                                      | `fluidPage()`, `titlePanel()`, `sidebarLayout()`, `sidebarPanel()`, `selectInput()`, `mainPanel()`, `plotOutput()`                                                                  |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          |                                                                                                                                                      |
|                                                                                       | `r advdate(wed,4)`  | Building the server          | `shiny`                                                      | `renderPlot()`, `shinyApp()`                                                                                                                                                        |       [ðŸ“–](https://muse-jhu-edu.proxygw.wrlc.org/article/225602 "Huntington")       |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          |                                  [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 5.1 quiz")                                  |
|                        [5.2](/modules/module-5.2 "Module 5.2")                        | `r advdate(thur,4)` | Line chart app setup         | `fredr`                                                      | `fredr_set_key()` , `as.Date()` , `Sys.Date()` ,                                                                                                                                    |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          |                                                                                                                                                      |
|                                                                                       | `r advdate(fri,4)`  | Building the UI              | `shiny`                                                      | `column()`, `wellPanel()`, `helpText()`, `sliderInput()`                                                                                                                            |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          |                                           [âœï¸](/project/project-assignment-2.html "Project assignment 2")                                            |
|                                                                                       | `r advdate(sat,4)`  | Building the server          | `shiny`, `fredr`                                             | `reactive()`, `fredr()`, `fred_indicator()`                                                                                                                                         |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          | [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 5.2 quiz") [ðŸ§®](/assignments/coding-assignment-5.html "Coding assignment 5") |
|                     [6.1](/modules/module-6.1.html "Module 6.1")                      | `r advdate(mon,5)`  | TBD                          |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          |                                                                                                                                                      |
|                                                                                       | `r advdate(tues,5)` | TBD                          |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                               |                                                                                                                                                             |                                                                                                                                                      |
|                                                                                       | `r advdate(wed,5)`  | TBD                          |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                               |                                                                                                                                                             |                                                                                                                                                      |
|                     [6.2](/modules/module-6.2.html "Module 6.2")                      | `r advdate(thur,5)` | TBD                          |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                               | ðŸ–¥ï¸                                                                                                                                                          |                                                                                                                                                      |
|                                                                                       | `r advdate(fri,5)`  | TBD                          |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                               |                                                                                                                                                             |                                                                                                                                                      |
|                                                                                       | `r advdate(sat,5)`  | TBD                          |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                               |                                                                                                                                                             |                                           [âœï¸](/project/project-assignment-3.html "Project assignment 3")                                            |
:::
