---
title: "Project Assignment"
---

## Overview

For your final project in this course, you will be producing a short "report" with some data visualizations embedded in it. The purpose of this assignment is to give you an opportunity to practice incorporating basic data visualizations into your workflow. You will render your Quarto document as either an HTML or revealjs slides and upload the finished product to [Quarto Pub](https://quartopub.com/). Then you will share the link with the class on Discord. 

You can use this document as a scratch document to create your visualizations and then ultimately convert it to your final document or presentation by changing the header titles and inserting your own text. Or, you can create and render your final document in a separate file.  

## Step 1: Give an overview of your topic (10 pts.)

*Give the reader a brief sense of the topic and why you chose it. Is there a question you are trying to answer with your data? What is that question and why is it important? Could be bullet points for a slide show or a few sentences for a document*

## Step 2: Give an overview of your data (10 pts.)

*Provide a brief overview of your data. You could include some summary statistics or just talk about what the main variables of interest are and how they relate to the topic you are interested.*

## Step 3: Make a bar chart (10 pts.)

*Make a bar chart to include your presentation or document. Give it appropriate labels, an accessible color scheme and a nice theme. If your are making a document, include a few lines to explain what the visualization tells us.*

## Step 4: Make a line chart (10 pts.)

*Make a line chart to include your presentation or document. Give it appropriate labels, an accessible color scheme and a nice theme. Make it interactive if you like.*

## Step 5: Make a scatter plot (10 pts.)

*Make a scatter plot to include your presentation or document. Give it appropriate labels, an accessible color scheme and a nice theme. Make it interactive if you like.*

## Step 6: Make another visualization of your choice (10 pts.)

*Make a another visualization of your choice. Give it appropriate labels, an accessible color scheme and a nice theme. Make it interactive if you like.*

## Step 7: Add additional text or slides for context (10 pts.)

*Now go back and add some conext to your slide show or document. If doing a slide show, add some slides with some additional information before and after your visualizations. If a document, write some text explaining the point of the visualization and what we learn from it.*

## Step 8: Enhance your document or presentation (10 pts.)

*Add some styling to your document. This could be a different font or color scheme. For presentations, you could try adding a logo and adjusting how slides transition or some of the other bells and whistles we discussed in class. For documents, you could add aditional sections or some references. Look at the Quarto documentation for ideas. Be creative!*

## Step 9: Render and upload document to Quarto Pub (10 pts.)

*Render your document and publish it to Quarto as we did in class by typing `quarto publish quarto-pub` in the terminal. Make sure you have set up a Quarto Pub account first.*

## Step 10: Post your link to Discord and reflect (10 pts.)

*Post the link of your Quarto Pub document on the class Discord server and reflect on your document and what you learned from the exercise. Finally, comment on at least one other student's post in the server. Provide positive feedback and say something about what you learned from their document or presentation.*



